CREATE TABLE ACCOUNT
(
    IBAN              VARCHAR(32)    NOT NULL,
    ACCOUNT_OWNER     VARCHAR(64)    NOT NULL,
    TYPE              VARCHAR(64)    NOT NULL,
    BALANCE           DECIMAL(16, 2) NOT NULL,
    REFERENCE_ACCOUNT VARCHAR(64),
    CURRENCY          VARCHAR(3)     NOT NULL
);
