# create account
POST http://localhost:8080/api/v1/accounts
Content-Type: application/json

{
  "iban": "DE63120300001234123435",
  "accountOwner": "Max Liemant",
  "type": "SAVING",
  "referenceAccount": "DE23120300001234123412",
  "currency": "EUR"
}

### get all accounts
GET http://localhost:8080/api/v1/accounts
Accept: application/json

### get checking accounts
GET http://localhost:8080/api/v1/accounts?accountType=CHECKING,SAVING
Accept: application/json

### get account by iban
GET http://localhost:8080/api/v1/accounts/DE23120300001234123412
Accept: application/json

### lock account
PUT http://localhost:8080/api/v1/accounts/DE23120300001234123412/lock
Accept: application/json

### unlock account
PUT http://localhost:8080/api/v1/accounts/DE23120300001234123412/unlock
Accept: application/json
